title: Alexis BRENON
url: http://alexisbrenon.github.io/
author: Alexis BRENON
linkedin: https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile
twitter: AlexisBRENON
github: AlexisBRENON

exclude: [bower_components]
