title: Alexis BRENON
protocol: https
url: alexisbrenon.github.io/
author: Alexis BRENON
linkedin: https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile
twitter: AlexisBRENON
github: AlexisBRENON

exclude: [readme.md, _config_local.yml, docker-compose.yml]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      excerpt_separator: "<!-- more -->"
      author: "Alexis BRENON"

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-coffeescript

sass:
    sass_dir: _sass
    style: :compressed
