title: Alexis BRENON Personal Website
author: Alexis BRENON
linkedin: https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile
twitter: AlexisBRENON
github: AlexisBRENON

exclude: [bower_components]
sass:
  load_paths:
    - _sass
    - bower_components/foundation/scss
