title: Alexis BRENON
url: http://alexisbrenon.github.io/
author: Alexis BRENON
linkedin: https://www.linkedin.com/profile/public-profile-settings?trk=prof-edit-edit-public_profile
twitter: AlexisBRENON
github: AlexisBRENON

exclude: [bower_components, bower.json, config.rb, Gemfile, Gemfile.lock, readme.md]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      excerpt_separator: "<!-- More -->"
      author: "Alexis BRENON"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: drafts
    values:
      layout: "post"
      excerpt_separator: "<!-- More -->"
      author: "Alexis BRENON"

gems:
  - jemoji
  - jekyll-sitemap
