version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
    entrypoint:
      - jekyll
    command:
      - serve
      - --config
      - _config_local.yml
